# Numpy
- 파이썬에서 수학적 계산을 쉽게 할 수 있도록 도와주는 라이브러리
- 파이썬에서 행렬관련 계산을 빠르게 해주는 패키지
- ndarray: 행렬이라고 생각 -> nd = n차원을 의미 (n dimensional)
- 주로 Tensorflow 나 pytorch, keras 등의 머신러닝 프레임워크에서 ndarray를 사용

## 1. Numpy 배열(Array) 생성하기

### np.array() : 입력받은 파이썬 리스트를 ndarray 형태로 변형
- 대괄호 n개수 = n차원
    - 대괄호가 추가될수록 차원도 추가 !!
- U(Uni-code) n (Data-size)

In [1]:
# 모듈 불러오기

import numpy as np

In [3]:
# 1차원 배열 생성

array = np.array(["A","B","C","D","E"]) # 벡터, 1차원 행렬



In [4]:
print(array.shape) # array 안에 있는 요소들의 개수

(5,)


In [6]:
print(array.shape) # array 안에 있는 요소들의 개수
print(array.ndim) # array의 차원
print(array.dtype) # array의 데이터 타입 확인

(5,)
1
<U1


In [7]:
#2차원 배열 생성

array2 = np.array([["A","B","C"] , ["D","E","F"]])
array2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [8]:
print(array2.shape)
print(array2.ndim)
print(array2.dtype)

(2, 3)
2
<U1


In [17]:
# 3차원 배열 생성

array3 = np.array(
[
    [["A","B","C"], ["D","E","F"]],
    [["A","B","C"], ["D","E","F"]],
])

array3

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['A', 'B', 'C'],
        ['D', 'E', 'F']]], dtype='<U1')

In [16]:
print(array3.shape) #2 by 2 by 3 
print(array3.ndim)
print(array3.dtype)

(2, 2, 3)
3
<U1


## 2. Numpy 형상 관련 함수

- astype() - ndarray 타입변환
    - astype : 내가 원하는 타입으로 변환
    - astype() -> ndarray의 타입을 변경 (int -> str, str -> int)

In [19]:
# array4 = np.array(["1","2","3","4","5"]) 문자
array4 = np.array([1,2,3,4,5])
print(array4.dtype)

array4 = array4.astype(np.float64)
print(array4.dtype)

int32
float64


## 3.Numpy 인덱싱 & 슬라이싱

In [21]:
#1차원 인덱싱

arr = np.arange(1,10) # 나중에 np.arrange(excel)

print(arr) # 전체 데이터 가져오기
print(arr[5]) # 6번째 데이터 가져오기
print(arr[-1]) # 맨 끝데이터 가져오기
print(arr[0:4]) #0~ 3번쨰 데이터 가져오기
print(arr[:]) # 전체 데이터 가져오기
print(arr > 7) # 7 초과한 숫자 T/F 로 표현
print(arr[arr>7]) # 7 초과한 숫자 표현
print(arr[~(arr>7)]) # 7 초과한 안된 숫자 표현


[1 2 3 4 5 6 7 8 9]
6
9
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[False False False False False False False  True  True]
[8 9]
[1 2 3 4 5 6 7]


In [22]:
print(arr > 6)
# 5보다 큰 데이터가 뭔지 알려줌 (true, false)
print(arr[arr>6])
#true 인것만 담아주기

[False False False False False False  True  True  True]
[7 8 9]


## 4.Numpy 연산 
- 배열 연산 필요성 -> 새로운 컬럼 추가해서 신규 데이터 생성 가능

In [24]:
#배열 연산

arr1 = np.array([[1,2,], [3,4]])
arr2 = np.array([[5,6,], [7,8]])

In [ ]:
#더하기

add = np.add(arr1,arr2)
print(add)
print(arr1+arr2)


In [ ]:
#곱하기

multiply = np.multiply(arr1,arr2)
print(multiply)
print(arr1*arr2)

In [ ]:
#최대값

np.max(arr1)
np.max(arr2)

In [40]:
#최대값의 인덱스

np.argmax(arr1) # arr1에서 최대값은 4이고, 3번쨰 값
np.argmax(arr2) # arr2 에서 최대값은 8이고, 3번쨰 값

3

In [42]:
#최소값

np.min(arr1)
np.min(arr2)

5

In [41]:
# 최소값의 인덱스

np.argmin(arr1) # arr1에서 최소값은 1이고, 0번쨰 값
np.argmin(arr2)  # arr2에서 최소값은 5이고, 0번쨰 값

0

In [43]:
#행렬의 내적

arr1.dot(arr2)

array([[19, 22],
       [43, 50]])